name: Deploy to Preview Channel

on:
  pull_request:
    paths:
      - plordle/lib/**
      - plordle/assets/**
      - plordle/pubspec.yaml
      - plordle/pubspec.loc

jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    steps:      
      - name: Git Checkout
        uses: actions/checkout@v4
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          flutter-version: 3.29.0
      - name: Build 
        run: |
          cd plordle
          flutter --version
          flutter pub get
          flutter build web
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_PLORDLE }}"
          expires: 3d
          projectId: plordle
          entrypoint: plordle/